* Python

   | Project    | Semantically versioned                             | Size     | Results    |
   |------------+----------------------------------------------------+----------+------------|
   | requests   | Yes, officially                                    | 4500 LOC | [[requests]]   |
   | simplejson | Seems like it, not officially                      | 2000 LOC | [[simplejson]] |
   | docopt     | Seems like it, not officially                      | 600 LOC  | [[docopt]]     |
   | hashids    | "We try to follow Semver, but check the changelog" | 300 LOC  | [[hashids]]    |

* Java

  | Project | Semantically versioned                         | Size      | Results |
  |---------+------------------------------------------------+-----------+---------|
  | mockito | "semantic versioning is rigorously maintained" | 11000 LOC | [[mockito]] |

* Evaluations
** requests

   From v1.0.0 to v2.13.0.

   - One misnamed tag
   - Removing random utility methods and classes (that weren't private)
   - New entities appearing and considering that to be "features"
   - General effort not to break function signatures -- new arguments
     have default values
   - One version removing methods like =is_py30=, =is_py31=, =is_py32=
     and so on (methods you don't expect the program to use, should
     have been private),
   - v2.6.0 starts supporting bytearrays, structural typing didn't catch it
     -- maybe a bug?
   - non-"exported" entities also considered, leads to large number of "breaking changes"
   - small modifications to signatures not considered features
   - function alias removed in v2.8.0, not considered breaking
   - v2.10.0 adds new feature (SOCKS proxy) without changing API

   Main problems stem from:
   - Not considering utility methods and classes to be part of API, even though
     they technically are.
   - Giving different subjective weight to changes, so e.g. removing a
     function alias is not considered breaking, or some random iterator.
     Also, if there's been only one breaking change, not mentioned in changelog and not
     bumping major version.
   - Features are introduced with no changes to the API (/autobump's problem?/)

   *Summary*: Autobump was much more conservative and proposed many more breaking changes.

   | 44 total | 21 different w/ structural | 19 different w/o structural | (50%) *FIRST DIFF*                     |
   |          | 16 major changes           | 10 major changes            |                                        |
   |          | 19 different w/ structural | 15 different w/o structural | (35%) *SECOND DIFF, only intended API* |
   |          | 16 major changes           | 9 major changes             |                                        |

   Excluding only obvious stuff:
   #+BEGIN_SRC diff
     --- structural  2017-01-27 23:17:36.158361209 +0000
     +++ nonstructural   2017-01-27 23:16:59.534449019 +0000
     @@ -1,21 +1,19 @@
      v1.0.3 --- v1.0.4 should have been v1.0.3 --- 2.0.0
      v1.0.4 --- v1.1.0 should have been v1.0.4 --- 2.0.0
      v1.1.0 --- v1.2.0 should have been v1.1.0 --- 2.0.0
      v1.2.0 --- v1.2.1 should have been v1.2.0 --- 2.0.0
      v1.2.1 --- v1.2.2 should have been v1.2.1 --- 2.0.0
      v2.0 --- v2.0.0 should have been v2.0 --- 2.0.1
      v2.0.0 --- v2.0.1 should have been v2.0.0 --- 3.0.0
     -v2.0.1 --- v2.1.0 should have been v2.0.1 --- 3.0.0
      v2.2.1 --- v2.3.0 should have been v2.2.1 --- 3.0.0
      v2.3.0 --- v2.4.0 should have been v2.3.0 --- 3.0.0
     -v2.4.1 --- v2.4.2 should have been v2.4.1 --- 3.0.0
     -v2.4.2 --- v2.4.3 should have been v2.4.2 --- 3.0.0
     +v2.4.1 --- v2.4.2 should have been v2.4.1 --- 2.5.0
     +v2.4.2 --- v2.4.3 should have been v2.4.2 --- 2.5.0
      v2.5.1 --- v2.5.2 should have been v2.5.1 --- 3.0.0
      v2.5.3 --- v2.6.0 should have been v2.5.3 --- 2.5.4
      v2.7.0 --- v2.8.0 should have been v2.7.0 --- 3.0.0
     -v2.8.1 --- v2.9.0 should have been v2.8.1 --- 3.0.0
      v2.9.1 --- v2.9.2 should have been v2.9.1 --- 2.10.0
     -v2.9.2 --- v2.10.0 should have been v2.9.2 --- 3.0.0
     +v2.9.2 --- v2.10.0 should have been v2.9.2 --- 2.9.3
      v2.10.0 --- v2.11.0 should have been v2.10.0 --- 3.0.0
      v2.11.1 --- v2.12.0 should have been v2.11.1 --- 3.0.0
     -v2.12.1 --- v2.12.2 should have been v2.12.1 --- 3.0.0
     +v2.12.1 --- v2.12.2 should have been v2.12.1 --- 2.13.0
   #+END_SRC

   Excluding utility files and other unintended stuff:
   #+BEGIN_SRC diff
     --- structural  2017-01-27 23:22:28.241684490 +0000
     +++ nonstructural   2017-01-27 23:21:59.009750667 +0000
     @@ -1,19 +1,15 @@
      v1.0.3 --- v1.0.4 should have been v1.0.3 --- 2.0.0
      v1.1.0 --- v1.2.0 should have been v1.1.0 --- 2.0.0
      v1.2.0 --- v1.2.1 should have been v1.2.0 --- 2.0.0
      v1.2.1 --- v1.2.2 should have been v1.2.1 --- 2.0.0
      v2.0 --- v2.0.0 should have been v2.0 --- 2.0.1
      v2.0.0 --- v2.0.1 should have been v2.0.0 --- 2.1.0
     -v2.0.1 --- v2.1.0 should have been v2.0.1 --- 3.0.0
      v2.2.1 --- v2.3.0 should have been v2.2.1 --- 3.0.0
      v2.3.0 --- v2.4.0 should have been v2.3.0 --- 3.0.0
     -v2.4.1 --- v2.4.2 should have been v2.4.1 --- 3.0.0
     -v2.4.2 --- v2.4.3 should have been v2.4.2 --- 3.0.0
     +v2.4.1 --- v2.4.2 should have been v2.4.1 --- 2.5.0
      v2.5.1 --- v2.5.2 should have been v2.5.1 --- 3.0.0
      v2.5.3 --- v2.6.0 should have been v2.5.3 --- 2.5.4
      v2.7.0 --- v2.8.0 should have been v2.7.0 --- 3.0.0
     -v2.8.1 --- v2.9.0 should have been v2.8.1 --- 3.0.0
      v2.9.1 --- v2.9.2 should have been v2.9.1 --- 2.10.0
     -v2.9.2 --- v2.10.0 should have been v2.9.2 --- 3.0.0
     +v2.9.2 --- v2.10.0 should have been v2.9.2 --- 2.9.3
      v2.10.0 --- v2.11.0 should have been v2.10.0 --- 3.0.0
     -v2.12.1 --- v2.12.2 should have been v2.12.1 --- 3.0.0
   #+END_SRC

** simplejson

   From v3.0.0 to v3.10.0

   39 versions, 6 different w/ both structural and nonstructural (15%)
   Only 1 misidentified breaking change, authors declared patch releases
   as feature releases

   - entities moved to another module, authors bumped the minor version
     (only breaking change proposal)
   - 3.2.0 -- 3.3.0 was definitely a bugfix, maybe an important one?
   - 3.3.3 -- 3.4.0 changed setup.py a bit, considered it a feature
   - 3.5.3 -- 3.6.0 still definitely a bugfix
   - 3.6.5 -- 3.7.0 bugfix

   Package authors may be right:

   #+BEGIN_QUOTE
   It [minor version] MAY be incremented if substantial new
   functionality or improvements are introduced within the private
   code.
   #+END_QUOTE

   Main problems are:
   - Moving entities not considered breaking.
   - Changing behaviour of functions w/o changing their signature
     considered a feature.

   *Summary*: Autobump does not know what a 'substantial' new functionality is, i.e.
   it sometimes can't differentiate patch and feature releases. Actually follows Semver the best,
   even though it doesn't claim to do so!

   #+BEGIN_SRC diff
     v3.0.9 --- v3.1.0 should have been v3.0.9 --- 4.0.0
     v3.2.0 --- v3.3.0 should have been v3.2.0 --- 3.2.1
     v3.3.3 --- v3.4.0 should have been v3.3.3 --- 3.3.4
     v3.5.3 --- v3.6.0 should have been v3.5.3 --- 3.5.4
     v3.6.5 --- v3.7.0 should have been v3.6.5 --- 3.6.6
     v3.8.2 --- v3.9.0 should have been v3.8.2 --- 3.8.3
   #+END_SRC

** docopt

   From 0.1.0 to 0.6.2

   11 versions, 7 different w/ structural, 6 different w/o structural (63%)

   - author bumps minor number at breaking changes

   Autobump is actually wrong here, versions starting with
   0. allow breaking changes at any point:

      #+BEGIN_QUOTE
      Major version zero (0.y.z) is for initial development. Anything may
      change at any time. The public API should not be considered stable.

      Version 1.0.0 defines the public API. The way in which the version
      number is incremented after this release is dependent on this public
      API and how it changes.
      #+END_QUOTE

   #+BEGIN_SRC diff
     --- structural   2017-01-27 13:53:47.913150564 +0000
     +++ nonstructural   2017-01-27 13:53:52.153150544 +0000
     @@ -1,7 +1,6 @@
      0.1.1 --- 0.2.0 should have been 0.1.1 --- 1.0.0
      0.2.0 --- 0.3.0 should have been 0.2.0 --- 1.0.0
      0.3.0 --- 0.4.0 should have been 0.3.0 --- 1.0.0
     -0.4.0 --- 0.4.1 should have been 0.4.0 --- 1.0.0
      0.4.1 --- 0.4.2 should have been 0.4.1 --- 1.0.0
      0.4.2 --- 0.5.0 should have been 0.4.2 --- 1.0.0
      0.5.0 --- 0.6.0 should have been 0.5.0 --- 1.0.0
   #+END_SRC

** hashids

   From v0.8.0 to v1.2.0

   10 versions, 2 mismatching both w/ and w/o structural typing (20%)

   - one missing version
   - one renaming of functions (encrypt → encode) not considered breaking

   *Summary*: Autobump caught two author mistakes.

   #+BEGIN_SRC diff
     v0.8.1 --- v0.8.3 should have been v0.8.1 --- 0.8.2
     v1.0.1 --- v1.0.2 should have been v1.0.1 --- 2.0.0
   #+END_SRC
** mockito

   From v2.2.0 to v2.6.9

   - Very small additions, like one new method, overloaded method, exception or class considered patches
   - v2.2.21 --- v2.2.22 proposes a major change because of a wildcard import
   - v2.3.6 --- v2.3.9 versions skipped
   - v2.3.11 --- v2.4.0 introduced verification listeners, even though that already happened earlier
   - v2.4.5 --- v2.5.0 adds new features w/o changing API
   - v2.6.0 "prepares Android library for publication", even though changes to it happened before

   Main problems (/java_ast/):

   - Adding one or two new methods, classes, not considered a feature
   - Waiting for those to aggregate, then considered a feature release
     BUT! Autobump claims it's a patch because nothing changed since the last one,
     i.e. features were already present.
     (/Overly frequent releases?/)
   - Backwards compatibility strictly preserved, only Autobump failed

   | 64 versions | /java_ast/                                               | /java_native/ |
   |             | 16 different (25%)                                       |               |
   |             | only 1 major (because of wildcard /failure in autobump/) |               |
   |             | 11 feature additions                                     |               |

   java_ast:
   #+BEGIN_SRC text
     v2.2.2 --- v2.2.3 should have been v2.2.2 --- 2.3.0
     v2.2.10 --- v2.2.11 should have been v2.2.10 --- 2.3.0
     v2.2.11 --- v2.2.12 should have been v2.2.11 --- 2.3.0
     v2.2.19 --- v2.2.20 should have been v2.2.19 --- 2.3.0
     v2.2.21 --- v2.2.22 should have been v2.2.21 --- 3.0.0
     v2.3.0 --- v2.3.1 should have been v2.3.0 --- 2.4.0
     v2.3.1 --- v2.3.2 should have been v2.3.1 --- 2.4.0
     v2.3.2 --- v2.3.3 should have been v2.3.2 --- 2.4.0
     v2.3.6 --- v2.3.9 should have been v2.3.6 --- 2.3.7
     v2.3.9 --- v2.3.10 should have been v2.3.9 --- 2.4.0
     v2.3.11 --- v2.4.0 should have been v2.3.11 --- 2.3.12
     v2.4.0 --- v2.4.1 should have been v2.4.0 --- 2.5.0
     v2.4.5 --- v2.5.0 should have been v2.4.5 --- 2.4.6
     v2.5.0 --- v2.5.1 should have been v2.5.0 --- 2.6.0
     v2.5.1 --- v2.5.2 should have been v2.5.1 --- 2.6.0
     v2.5.7 --- v2.6.0 should have been v2.5.7 --- 2.5.8
   #+END_SRC
